server:
  port: 8083

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: rating
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      database: ${DATASOURCE_NAME}
      uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_DOMAIN}:27017/raitings?authSource=admin
kafka:
  bootstrap-servers: ${BOOTSTRAP_SERVERS}:9092
