server:
  port: 8083

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: rating
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      database: ${DATASOURCE_NAME}
      uri: mongodb+srv://${DATASOURCE_USERNAME}:${DATASOURCE_PASSWORD}@cluster0.lowllaw.mongodb.net/?retryWrites=true&w=majority


eureka:
  client:
    service-url:
      default-zone: http://${EUREKA_HOST}:8761/eureka

kafka:
  bootstrap-servers: ${BOOTSTRAP_SERVERS}:9092
